### ISSUE TITLE
Remove deprecated code from scrript proxy action

### ISSUE THREAD

**Issue by brusch** [pimcore/admin-ui-classic-bundle#16]
See: 
https://github.com/pimcore/admin-ui-classic-bundle/blob/d8bb3749655936727e448ae4c8bd4a81ba780bf2/src/Controller/Admin/MiscController.php#L149

We should also check whether we still need the script-proxy anyway ... ideally we could get rid of it.

**Comment by aryaantony92** [comment]
Removed the deprecated code in https://github.com/pimcore/admin-ui-classic-bundle/pull/59. Checked the usage of scriptProxyAction() method and it's used in minimising the js scripts on production mode. So, made the scriptProxyAction() as internal, so that we can remove the method in final release after implementing webpack/npm to minimise the scripts.
