### ISSUE TITLE
Are BundleManagerEvents really needed in that bundle

### ISSUE THREAD

**Issue by fashxp** [pimcore/admin-ui-classic-bundle#172]
see https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/src/Event/BundleManagerEvents.php

Same file also still exists in pimcore/pimcore, see https://github.com/pimcore/pimcore/blob/11.x/lib/Event/BundleManagerEvents.php, and is also used in PimcoreBundleManager, which lives in pimcore/pimcore

**Comment by dvesh3** [comment]
It was refactored here https://github.com/pimcore/pimcore/pull/14899/files and used in the [`PimcoreBundleManager`](https://github.com/pimcore/pimcore/pull/14899/files#diff-87f735c2c4ec9cb024ec57f767443b430d06270b0ba7c066cb13d35842b9c271R22).

These changes later reverted in merge from 10.6 into 11. https://github.com/pimcore/pimcore/commit/b8a31b3fa82c8f33c2399c51067df865aa00ec66#diff-87f735c2c4ec9cb024ec57f767443b430d06270b0ba7c066cb13d35842b9c271

Now, If we kick this file here and keep it in pimcore/pimcore then we have to remove the [upgrade notes](https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Upgrade_Notes/#extracted-core-functionality-) _"Moved BundleManagerEvents to AdminBundle. Please use Pimcore\Bundle\AdminBundle\Event\BundleManagerEvents instead of Pimcore\Event\BundleManagerEvents."_

**Comment by fashxp** [comment]
Mhm, but bundle manager lives in pimcore/pimcore, so the events also need to be there, right?

**Comment by dvesh3** [comment]
yes, right. I'm more concerned about removing the upgrade notes then as you would have to change it back to use the core class.

**Comment by fashxp** [comment]
Mhm, yes ... Not ideal

**Comment by dvesh3** [comment]
Fixed by #174
