### ISSUE TITLE
[Bug]: User settings checkbox "Memorize open tabs" has no effect

### ISSUE THREAD

**Issue by kneumann37** [pimcore/admin-ui-classic-bundle#327]
### Pimcore version

10.6.7; 11.0.12

### Steps to reproduce

User Settings provide a checkbox "Memorize open tabs" that is ticked per default.

### Actual Behavior

After logging out and in again all tabs no tabs are opened automatically.

### Expected Behavior

After logging out and in again the previous session's tabs are opened.

**Comment by dvesh3** [comment]
@kneumann37 Moved to the correct repo where it belongs.

**Comment by kingjia90** [comment]
I think that, at the current state, it was intended that after logging it would clear the memorized tabs
https://github.com/pimcore/admin-ui-classic-bundle/blob/bed29a3cc0321c1065a3ab43af73a32a4627f3af/templates/admin/login/login.html.twig#L50
(actually happens on the login form/page)
that's likely because it's stored in local storage and not strictly associated to any user id, therefore, if it wasn't clearing, the following user login would have the memorized tabs of the previously logged out one.
